/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author ferna
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        jLnombre = new javax.swing.JLabel();
        jTnombre = new javax.swing.JTextField();
        jLmatricula = new javax.swing.JLabel();
        jTmatricula = new javax.swing.JTextField();
        jLcadena = new javax.swing.JLabel();
        jTcadena = new javax.swing.JTextField();
        jBlimpiar = new javax.swing.JButton();
        jBaceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        background.setBackground(new java.awt.Color(51, 51, 51));

        jLnombre.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLnombre.setForeground(new java.awt.Color(204, 204, 204));
        jLnombre.setText("Ingresa Nombre:");

        jTnombre.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTnombre.setForeground(new java.awt.Color(153, 153, 153));
        jTnombre.setText("yazmany . . .");

        jLmatricula.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLmatricula.setForeground(new java.awt.Color(204, 204, 204));
        jLmatricula.setText("Ingresa Matricula:");

        jTmatricula.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTmatricula.setForeground(new java.awt.Color(153, 153, 153));
        jTmatricula.setText("1339767");

        jLcadena.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jLcadena.setForeground(new java.awt.Color(204, 204, 204));
        jLcadena.setText("Cadena a Validar:");

        jTcadena.setFont(new java.awt.Font("Rubik", 0, 14)); // NOI18N
        jTcadena.setForeground(new java.awt.Color(153, 153, 153));
        jTcadena.setText("1mnyjgccicyjgci.an3.1339767");
        jTcadena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcadenaActionPerformed(evt);
            }
        });

        jBlimpiar.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jBlimpiar.setForeground(new java.awt.Color(153, 153, 153));
        jBlimpiar.setText("Limpiar");

        jBaceptar.setFont(new java.awt.Font("Rubik Medium", 0, 14)); // NOI18N
        jBaceptar.setForeground(new java.awt.Color(204, 204, 204));
        jBaceptar.setText("Aceptar");

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcadena, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLnombre)
                    .addComponent(jLmatricula)
                    .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLcadena))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jBlimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jBaceptar)
                .addGap(170, 170, 170))
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLnombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLmatricula)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLcadena)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTcadena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBlimpiar)
                    .addComponent(jBaceptar))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTcadenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcadenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcadenaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBlimpiar;
    private javax.swing.JLabel jLcadena;
    private javax.swing.JLabel jLmatricula;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JTextField jTcadena;
    private javax.swing.JTextField jTmatricula;
    private javax.swing.JTextField jTnombre;
    // End of variables declaration//GEN-END:variables
}
